/* AUTH */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

// login 세션확인 구현/ 로그아웃 구현
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


/* MEMO */
export const MEMO_POST = "MEMO_POST";
export const MEMO_POST_SUCCESS = "MEMO_POST_SUCCESS";
export const MEMO_POST_FAILURE = "MEMO_POST_FAILURE";

export const MEMO_LIST = "MEMO_LIST";
export const MEMO_LIST_SUCCESS = "MEMO_LIST_SUCCESS";
export const MEMO_LIST_FAILURE = "MEMO_LIST_FAILURE";

export const MEMO_EDIT = "MEMO_EDIT";
export const MEMO_EDIT_SUCCESS = "MEMO_EDIT_SUCCESS";
export const MEMO_EDIT_FAILURE = "MEMO_EDIT_FAILURE";

export const MEMO_REMOVE = "MEMO_REMOVE";
export const MEMO_REMOVE_SUCCESS = "MEMO_REMOVE_SUCCESS";
export const MEMO_REMOVE_FAILURE = "MEMO_REMOVE_FAILURE";

export const MEMO_STAR = "MEMO_STAR";
export const MEMO_STAR_SUCCESS = "MEMO_STAR_SUCCESS";
export const MEMO_STAR_FAILURE = "MEMO_STAR_FAILURE";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

/* NOTICE */
export const NOTICE_POST = "NOTICE_POST";
export const NOTICE_POST_SUCCESS = "NOTICE_POST_SUCCESS";
export const NOTICE_POST_FAILURE = "NOTICE_POST_FAILURE";

export const NOTICE_LIST = "NOTICE_LIST";
export const NOTICE_LIST_SUCCESS = "NOTICE_LIST_SUCCESS";
export const NOTICE_LIST_FAILURE = "NOTICE_LIST_FAILURE";

export const NOTICE_EDIT = "NOTICE_EDIT";
export const NOTICE_EDIT_SUCCESS = "NOTICE_EDIT_SUCCESS";
export const NOTICE_EDIT_FAILURE = "NOTICE_EDIT_FAILURE";

export const NOTICE_REMOVE = "NOTICE_REMOVE";
export const NOTICE_REMOVE_SUCCESS = "NOTICE_REMOVE_SUCCESS";
export const NOTICE_REMOVE_FAILURE = "NOTICE_REMOVE_FAILURE";

export const NOTICE_STAR = "NOTICE_STAR";
export const NOTICE_STAR_SUCCESS = "NOTICE_STAR_SUCCESS";
export const NOTICE_STAR_FAILURE = "NOTICE_STAR_FAILURE";


/* Buy coffee */
export const BUY_COFFEE = "BUY_COFFEE";
export const BUY_COFFEE_SUCCESS = "BUY_COFFEE_SUCCESS";
export const BUY_COFFEE_FAILURE = "BUY_COFFEE_FAILURE";
